apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
  namespace: three-tier
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi             #Yes, in Kubernetes, when you create a PersistentVolumeClaim (PVC) like the one you've described, you typically do not need to create a PersistentVolume (PV) separately
